export const HOME = "Home";
export const SHOWS = "TV Shows";
export const SEARCH = "Search";
export const WELCOMESCREEN = "Welcome Screen";
export const MOVIES = "Movies";
export const MOVIEDETAIL = "Movie Detail";
export const PROFILESCREEN = "Profile Screen";
export const SIGNUP = "Signup";
export const LOGIN = "Login";
