import { StyleSheet } from "react-native";
import { SIZES } from "../../../../constants";
export default StyleSheet.create({
  container: {
    position: "absolute",
    top: 0,
    left: 0,
    bottom: 0,
    right: 0,
  },
  background: {
    position: "absolute",
    height: 100,
    left: 0,
    bottom: 0,
    right: 0,
    // backgroundColor: '#00000066',
  },
  fullScreen: {
    position: "absolute",
    top: 0,
    left: 0,
    bottom: 0,
    right: 0,
  },
  fullScreenCenter: {
    // position: 'absolute',
    // top: 0,
    // left: 0,
    // bottom: 0,
    // right: 0,
    // flex: 1,
    alignItems: "center",
    justifyContent: "center",
  },
  controlsContainer: {
    position: "absolute",
    bottom: 0,
    left: 20,
    right: 20,
    paddingLeft: 10,
    paddingRight: 10,
    // padding: 10,
    // paddingBottom: 20,
  },
  bottomControlsContainer: {
    flexDirection: "row",
    justifyContent: "space-between",
  },
  errorContainer: {
    position: "absolute",
    top: 0,
    left: 0,
    bottom: 0,
    right: 0,
    alignItems: "center",
    justifyContent: "center",
  },
  error: {
    textAlignVertical: "center",
    textAlign: "center",
    fontSize: 16,
    paddingLeft: 50,
    paddingRight: 50,
    color: "white",
  },
  playButton: {
    width: 90,
    height: 90,
    tintColor: "#fff",
    minWidth: 130,
  },
  pauseButton: {
    width: 120,
    height: 120,
    tintColor: "#fff",
    minWidth: 130,
  },
  menuIcon: {
    width: 30,
    height: 30,
  },
  timeLabel: {
    marginLeft: 20,
    height: 20,
    alignSelf: "center",
  },
  thumbnailContainerCarousel: {
    justifyContent: "center",
    marginBottom: 15,
  },
  thumbnailContainerSingle: {
    marginBottom: 15,
  },
  thumbnailCurrentCarousel: {
    borderColor: "#ffc50f",
    borderWidth: 2,
  },
  thumbnailCurrentSingle: {
    borderWidth: 0,
  },
  thumbnailCarousel: {
    margin: 4,
  },
  recommendTitle: {
    fontFamily: "Sora-Bold",
    color: "#fff",
    textAlign: "center",
    marginBottom: 5,
    fontSize: 15,
  },
  recommendContainer: {
    width: SIZES.height * 0.3,
    height: SIZES.width * 0.35,
    borderRadius: 2,
    marginHorizontal: 5,
    marginVertical: 5,
    justifyContent: "flex-end",
    borderRadius: 5,
    backgroundColor: "#fff",
  },
  recommendImage: {
    position: "absolute",
    top: 0,
    bottom: 0,
    left: 0,
    right: 0,
    borderRadius: 5,
  },
  touchableContainer: {
    position: "absolute",
    top: 3,
    bottom: 3,
    left: 3,
    right: 3,
    borderRadius: 5,
    justifyContent: "flex-end",
  },
  linearBorder: {
    // flexDirection: "row",
    // width: "90%",
    // height: SIZES.height < 900 ? 65 : 75,
    // paddingHorizontal: 1.5,
    // paddingVertical: 1.5,
    flex: 1,
    // paddingTop: 1.5,
    // paddingBottom: 1.5,
    // paddingLeft: 1.5,
    // paddingRight: 1.5,
    // alignSelf: "center",
    // borderWidth: 1,
    // borderColor: "deepskyblue",
    borderRadius: 5,
    // alignItems: "center",
    // marginVertical: 8,
  },
});
