require_relative '../node_modules/react-native/scripts/react_native_pods'
require_relative '../node_modules/@react-native-community/cli-platform-ios/native_modules'
source 'https://github.com/bitmovin/cocoapod-specs.git'

platform :ios, '12.0'

target 'FliikaMobileRN' do
  config = use_native_modules!



  use_react_native!(
    :path => config[:reactNativePath],
    # to enable hermes on iOS, change `false` to `true` and then install pods
    :hermes_enabled => false
  )


  
  #pod 'takeoffmedia-react-native-bitmovin-player', :path => '../..'
  # pod 'SDWebImage', git: "https://github.com/SDWebImage/SDWebImage.git", tag: "5.1.0"
  # pod 'SDWebImageWebPCoder', git: "https://github.com/SDWebImage/SDWebImageWebPCoder.git", tag: "0.3.0"
  # pod 'libwebp', git: "https://github.com/SDWebImage/libwebp-Xcode", tag: "1.1.0"

  pod 'BitmovinAnalyticsCollector/Core', git: 'https://github.com/bitmovin/bitmovin-analytics-collector-ios.git', tag: '1.20.0-beta2'
  pod 'BitmovinAnalyticsCollector/BitmovinPlayer', git: 'https://github.com/bitmovin/bitmovin-analytics-collector-ios.git', tag: '1.20.0-beta2'
  pod 'BitmovinPlayer', git: 'https://github.com/bitmovin/bitmovin-player-ios-sdk-cocoapod.git', tag:'2.66.0'
  target 'FliikaMobileRNTests' do
    inherit! :complete
    # Pods for testing
  end

  # Enables Flipper.
  #
  # Note that if you have use_frameworks! enabled, Flipper will not work and
  # you should disable the next line.
  #use_flipper!()


  post_install do |installer|
    installer.pods_project.build_configurations.each do |config|
      config.build_settings["EXCLUDED_ARCHS[sdk=iphonesimulator*]"] = "arm64"
    end
    end
  end